app/config/sculpin_site.yml
source/_layouts/default.twig

Adicionado footer

---

source/index.md

Modificando o tempo de transição entre as imagens do carrossel da home.

Alteração do tempo de transição de imagens do Carrosel da home.

---

source/sobre.md

Minha bio no site da Lyseon Tech.

Atualização do texto sobre Daiane Alves.

---

source/_layouts/footer.twig
source/css/main.css

Tirei a imagem da logo, o que diminuiu bastante no rodapé e nas redes sociais eu coloquei o ícone de cada uma e tirei o nome. Ainda há alterações que devem ser feitas no CSS para acertar o alinhamento das li e do copyright.

Ajustes diversos no rodapé

---

.travis.yml

keep-history: true
Alteração para manter o histórico de commits no repo dos estáticos

Mantendo o histórico de commits

---

source/_assets/sass/main.scss
source/_layouts/page.blade.php
source/sobre.blade.php

margem de elemento com posicionamento incorreto corrigida

remoção da section "quem somos"

---

composer.lock
package-lock.json
package.json

Atualização de versões de pacotes para correções de possíveis problemas de segurança.

Atualização de versões de pacotes

---

source/_assets/sass/main.scss
source/contato.blade.php

Empurrando rodapé para o fim da página

---

source/_assets/sass/main.scss
source/contato.blade.php

Empurrando rodapé para o fim da página
#59

Merge da develop: Empurrando rodapé

---

source/_assets/sass/main.scss
source/_layouts/header.blade.php
source/index.blade.php
source/matomo.blade.php

Correção na logo
Adição do matomo

Matomo e logo

---

css/style.css
index.html

Alteração do background

---

.docker/php7/Dockerfile
source/_layouts/master.blade.php

Implementação da integração com o widget de LiveChat do rocket.chat
Rocket.chat já está configurado e pode ser testado em:
https://vitormattos.github.io/teste-livechat/

Rocket chat

---

babel.config.js
jest.config.js
package.json
yarn.lock

Add jest library to create tests for components, functions.

 Library test

---

source/_assets/sass/main.scss
source/nextcloud.blade.php

button: "Saiba mais". The url redirect to librecode telegram
copywrite: "Nextcloud é uma marca registrada de Nextcloud GmbH."

add button and copywrite nextcloud

---

source/_layouts/footer.blade.php
source/nextcloud.blade.php

Changes:
- Menu
| Before | After |
| ------ | ------ |
| ![image](https://github.com/LibreCodeCoop/site/assets/54338576/192dbd54-50b3-45c7-bd7e-ca4144e4b2ed) | ![image](https://github.com/LibreCodeCoop/site/assets/54338576/9c2ba200-5dbd-40f6-8076-7ef836f9f47b) |
- Div near of the footer, change the style
| Before | After |
| ------ | ------ |
| ![image](https://github.com/LibreCodeCoop/site/assets/54338576/e680b45a-e861-400c-8a4f-a1e2f05ec5d7) | ![image](https://github.com/LibreCodeCoop/site/assets/54338576/4614ab70-6c96-47bd-898d-d88d08d4266f) |

changes on nextcloud page

---

.docker/php/Dockerfile
.docker/php/entrypoint.sh
docker-compose.yml

Motivation:
I got the error "npm: command not found", to fix I added the node to env PATH

chore: update node setup

---

source/_layouts/main.blade.php

chore: add support to Open Graph

---

source/index.blade.php

Remove option patreon as sponsor
|Before|After|
|-----------------------|-----------------------|
|![image](https://github.com/user-attachments/assets/17db4251-694e-4389-8d99-6face2365edb)|![image](https://github.com/user-attachments/assets/7d5b1409-2e84-4136-b3cb-a3290d6a59d8)|

remove patreon sponsor

---

source/_layouts/main.blade.php

|🏚️ Before|🏡 After|
|---|---|
|![Screenshot_20241009_195222](https://github.com/user-attachments/assets/e40979ad-80e8-406d-b538-aa7c1c589d54)|![Screenshot_20241009_195205](https://github.com/user-attachments/assets/486d4f53-a9fe-426c-9a77-c41db54d150f)|

chore: change logo

---

source/jobs/cursos.md
source/jobs/entrevistas.md
source/jobs/exercicios/app.md
source/jobs/exercicios/comercial.md
source/jobs/exercicios/docker.md
source/jobs/exercicios/good-first-issue.md
source/jobs/exercicios/index.md
source/jobs/index.blade.php
source/jobs/pre-requisitos.md
source/jobs/requisitos-backend.md
source/jobs/requisitos-frontend.md
source/jobs/requisitos-infraestrutura.md
source/jobs/videos.md

Objetivo: trazer pontos de melhoria para deixar o processo de seleção de novos sócios mais claro e documentado.
Atividades:
Referência: https://github.com/LibreSign/site/pull/329

chore: reestruturação do "Coopere conosco"

---

source/_assets/js/main.js
source/_assets/sass/main.scss

Related issue: #259
This PR adds a navigation status indicator to help users navigate the site.
https://github.com/user-attachments/assets/98071c3d-d173-4430-bb1b-55b66164aa34

feat: add navbar status indication.
